### ISSUE TITLE
4 hours cost per epoch in step2_train_nodule_detector.py in my computer. How to solve that?

### ISSUE THREAD

**Issue by guyucowboy** [juliandewit/kaggle_ndsb2017#19]
Hi, juliandewit:
     Great work! Thank you for sharing your code. 
     I have a question to ask you. When I ran the step2_train_nodule_detector.py, I found that 4 hours were used for each epoch. It just waited for 3 hours and  ran model.fit_generator for 1 hour. The gpu in my computer is GTX 980 Ti G1. How can I cut down the running time?
     Thanks!
Gu Yu

**Comment by guyucowboy** [comment]
After waiting for 4 hours, it prints :"Epoch 00008: val_loss did not improve"

**Comment by juliandewit** [comment]
I cannot say what is wrong. GPU seems good enough. I use an SSD for io speed.

**Comment by guyucowboy** [comment]
I mark it. I will try it when I have an SSD. 
Thank you!
