### ISSUE TITLE
Why 100 is added in the function dice_coef in step2_train_mass_segmenter.py

### ISSUE THREAD

**Issue by guyucowboy** [juliandewit/kaggle_ndsb2017#21]
Hi,juliandewit
Your source code helps me lot. I have another question to ask you. I found the function dice_coef at line 207 in step2_train_mass_segmenter.The function return (2. * intersection + 100) / (K.sum(y_true_f) + K.sum(y_pred_f) + 100). 
The definition of dice coef do not contain 100. It seems to be  (2. * intersection ) / (K.sum(y_true_f) + K.sum(y_pred_f) )
Why did you add 100 at both numerator and denominator? Thanks for you help.
Gu Yu

**Comment by juliandewit** [comment]
It worked better than 1 at a certain moment.
Never changed it back.
It's of no consequence

**Comment by guyucowboy** [comment]
Get it.
Thank you for your reply!
