### ISSUE TITLE
creating/locating masses_predictions.csv

### ISSUE THREAD

**Issue by teaghan** [juliandewit/kaggle_ndsb2017#29]
In step4_train_submissions.py you load a csv file as such:

mass_df = pandas.read_csv(settings.BASE_DIR + "masses_predictions.csv")

Is this file created somewhere in the previous steps? or is it one that is downloaded beforehand? I can't seem to find where it is created or located.

Thanks,
Teaghan

**Comment by abhi-kumar** [comment]
IT was resolved at https://github.com/juliandewit/kaggle_ndsb2017/issues/9

As Julian mentioned 
"
step2_train_mass_segmenter.py
Also has a predict phase.
This one will generate this file.

You can also leave it out. It will not change the score very much.
"

Regards,
Abhishek
