### ISSUE TITLE
How to process "slices[0].ImageOrientationPatient != [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]"

### ISSUE THREAD

**Issue by shartoo** [juliandewit/kaggle_ndsb2017#3]
What if there exist dicom whose `slices[0].ImageOrientationPatient != [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]` ? Should i just discard or do some other preprocess?

**Comment by juliandewit** [comment]
Hello,
The idea was to make all the slices uniform regarding orientation.
This is not 100% necessary but in general better.

If you encountered a new orientation in another dataset. You could ignore it and the effect will be minimal.
Even better would be to determine the 3d rotations/flips to get the result the same as all the rest.

Good luck.

**Comment by shartoo** [comment]
@juliandewit I have fixed this problem by rotation the image extracted from dicom if the  slope was not right, should i post here or pull a request?

**Comment by juliandewit** [comment]
I merged..
