### ISSUE TITLE
About ur documentation ....and codes for the lung nodule detection

### ISSUE THREAD

**Issue by bundelesneha05** [juliandewit/kaggle_ndsb2017#33]
hiii julian

 I am little bit confused about the ndsb dataset. you gave the two solutions for the preprocessing of the dataset.one is for luna dataset and ndsb dataset. from where ndsb dataset you got? also in the following link you showed that, you create the 3D chunks of the scans.How to create it exactly?

http://juliandewit.github.io/kaggle-ndsb2017/
 but in the LUNA 16 challenge they also given the documentation for the extraction of the patches. why are  you going for the 3D chunks of the scans rather than the patches obtained from the luna dataset???

 Thank you!!!

**Comment by juliandewit** [comment]
3d chunks work better than 2d patches

**Comment by bundelesneha05** [comment]
Thank You..!!!
But not getting any idea about NDSB3 Dataset......??? Is it same as that of the LUNA16 database...???

**Comment by mingrui** [comment]
I think this is National Data Science Bowl 3 data:
https://www.kaggle.com/c/data-science-bowl-2017/data

**Comment by juliandewit** [comment]
Like mingrui said

**Comment by bundelesneha05** [comment]
Thanks..!!!  I have one doubt  in setting.py file 
**BASE_DIR_SSD = "C:/werkdata/kaggle/ndsb3/".**... should  NDSB database  place here...????
AND 
**BASE_DIR = "D:/werkdata/kaggle/ndsb3/"** .....should LUNA database place here...????
As you gave two files for preprocessing for LUNA and NDSB dataset. Also...it  is all about dataset but you used th lidc .xml file for what....in step1_preprocess_luna16.py

**Comment by bundelesneha05** [comment]
Hi  julian....
 I  successfully run code for preprocessing of  NDSB data  but while doing for the LUNA  database I successfully extract the images in the .png format with corresponding mask but their are some doubts about the output at this step(as you said in your documentation  csv files also generated at this step along with the .png images)
1. I am getting an '_labels' folder in which csv file are saved (in the same directory where the lung mask are saved).
Files named as  given below, generated in the labels folder.  
**1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405_annos_excluded.csv
    1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405_annos_pos.csv**
2. I am unable to run ' load_lidc_xml' function.

3. Should 'xml_path' and 'xml_file'  taken from the resources-->luna16_annotation  folder ???? as  xml file are given  in this folder.
what  directory should I placed to these ..xml_path and xml_file..???

I am beginner to the python programming. So please help me to fix out coding problem.
kindly reply  the message `.....!!!!`

**Comment by bundelesneha05** [comment]
hii...
for making traincubes .csv files are required ,but in the github documentation you said only LUNA16 dataset gives the .csv files...what about the ndsb3 dataset....???is  the csv files related to this it manually created or we can use the ndsb_manual _labels from the resources folder..???...please reply...
