### ISSUE TITLE
Implementation of code...

### ISSUE THREAD

**Issue by bundelesneha05** [juliandewit/kaggle_ndsb2017#40]
Is any one completely run this codes,with a proper required outputs? Plz reply.
Thank you!

**Comment by ahasanpour** [comment]
Dear @bundelesneha05,

Why you use many question marks and dots in your sentences? This is not a polite way of asking.

But about your question, Yes I Could run.

**Comment by bundelesneha05** [comment]
Sorry for the mistake. I really don't know about the meaning behind this multiple dots and question marks.
Thank You!

**Comment by bundelesneha05** [comment]
Dear@ahasanpour ,
Have you got train cubes for luna16_train_cubes_auto, luna16_train_cubes_lidc, luna16_train_cubes_manual,
ndsb_train_cubes_manual?

**Comment by ahasanpour** [comment]
please follow issue #35
