### ISSUE TITLE
 ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by sathyapatel** [juliandewit/kaggle_ndsb2017#43]
I am getting this error when i ran **STEP1B_PREPROCESS_MAKE_TRAIN_CUBES.PY**  Error has thrown for some **luna16_manual_labels** files. i don't understand what's happening in some specific CSV files.
i have seen few .png images in **luna16_train_cubes_manual** folder.

**ERROR  SCREENSHOT**
Computer:  DESKTOP-AVK4MS4
1.3.6.1.4.1.14519.5.2.1.6279.6001.128881800399702510818644205032
0       1.3.6.1.4.1.14519.5.2.1.6279.6001.128881800399702510818644205032        2
1.3.6.1.4.1.14519.5.2.1.6279.6001.160216916075817913953530562493
1       1.3.6.1.4.1.14519.5.2.1.6279.6001.160216916075817913953530562493        1
1.3.6.1.4.1.14519.5.2.1.6279.6001.161002239822118346732951898613
1.3.6.1.4.1.14519.5.2.1.6279.6001.167919147233131417984739058859
3       1.3.6.1.4.1.14519.5.2.1.6279.6001.167919147233131417984739058859        1
1.3.6.1.4.1.14519.5.2.1.6279.6001.170825539570536865106681134236
4       1.3.6.1.4.1.14519.5.2.1.6279.6001.170825539570536865106681134236        1
1.3.6.1.4.1.14519.5.2.1.6279.6001.172845185165807139298420209778
5       1.3.6.1.4.1.14519.5.2.1.6279.6001.172845185165807139298420209778        3
1.3.6.1.4.1.14519.5.2.1.6279.6001.173931884906244951746140865701
6       1.3.6.1.4.1.14519.5.2.1.6279.6001.173931884906244951746140865701        2
1.3.6.1.4.1.14519.5.2.1.6279.6001.227968442353440630355230778531
7       1.3.6.1.4.1.14519.5.2.1.6279.6001.227968442353440630355230778531        1
1.3.6.1.4.1.14519.5.2.1.6279.6001.230491296081537726468075344411
8       1.3.6.1.4.1.14519.5.2.1.6279.6001.230491296081537726468075344411        1
1.3.6.1.4.1.14519.5.2.1.6279.6001.241717018262666382493757419144
9       1.3.6.1.4.1.14519.5.2.1.6279.6001.241717018262666382493757419144        1
1.3.6.1.4.1.14519.5.2.1.6279.6001.246225645401227472829175288633
Traceback (most recent call last):
  File "step1b_preprocess_make_train_cubes.py", line 271, in <module>
    make_pos_annotation_images_manual()
  File "step1b_preprocess_make_train_cubes.py", line 139, in make_pos_annotation_images_manual
    images = helpers.load_patient_images(patient_id, settings.LUNA16_EXTRACTED_IMAGE_DIR, "*" + CUBE_IMGTYPE_SRC + ".png")
  File "C:\Users\Sangryal\Downloads\sathya\helpers.py", line 78, in load_patient_images
    res = numpy.vstack(images)
  File "C:\Users\Sangryal\Anaconda3\lib\site-packages\numpy\core\shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate

**Comment by bundelesneha05** [comment]
I also facing same error ..while running the  **STEP1B_PREPROCESS_MAKE_TRAIN_CUBES.PY** ...!!!!!!!!!!!

**Comment by sathyapatel** [comment]
1.3.6.1.4.1.14519.5.2.1.6279.6001.246225645401227472829175288633
1.3.6.1.4.1.14519.5.2.1.6279.6001.188265424231150847356515802868
1.3.6.1.4.1.14519.5.2.1.6279.6001.273525289046256012743471155680

these above 3 files from **luna16_manual_labels** created a problem ..i removed it and rest of the files are perfect to generate cube images

**1.3.6.1.4.1.14519.5.2.1.6279.6001.161002239822118346732951898613** csv file..no data is present.. empty file..

@juliandewit could you please take a look here..what's happening in these above 3 files throwing an error.

**Comment by juliandewit** [comment]
Hello..
I'd say that they might be corrupt.
Maybe you vcan re-download them or completely ignore them.
3 patients will not make a big difference.

Regards,
  Julian.

**Comment by sathyapatel** [comment]
Thanks for your reply !!!
