### ISSUE TITLE
regarding the error in step2_train_nodule_detector.py

### ISSUE THREAD

**Issue by bundelesneha05** [juliandewit/kaggle_ndsb2017#50]
**I  run the script step2_nodule_detector.py  in which for,  model 2 on luna16 annotations + ndsb pos annotations I got following error,**

 File "<ipython-input-110-c02676e5595b>", line 2, in <module>
    train(train_full_set=True, load_weights_path=None, ndsb3_holdout=0, manual_labels=True, model_name="luna_posnegndsb_v1", fold_count=2)

  File "<ipython-input-107-cb207f0b9c24>", line 12, in train
    train_files, holdout_files = get_train_holdout_files(train_percentage=80, ndsb3_holdout=ndsb3_holdout, manual_labels=manual_labels, full_luna_set=train_full_set, fold_count=fold_count)

  File "<ipython-input-104-fe3fd07adb01>", line 113, in get_train_holdout_files
    pos_sample_path = pos_samples[pos_idx]

IndexError: list index out of range
Thanks in advance!
Please reply as soon as possible.

**Comment by juliandewit** [comment]
This is someting that must be debugged.
My hunch is that it cannot find any annotations.

**Comment by bundelesneha05** [comment]
thanks @juliandewit
