### ISSUE TITLE
settings.MANUAL_ANNOTATIONS_LABELS_DIR and  pos_labels_dir = settings.LUNA_NODULE_LABELS_DIR

### ISSUE THREAD

**Issue by bundelesneha05** [juliandewit/kaggle_ndsb2017#51]
In step3_predict_nodules.py, 
settings.MANUAL_ANNOTATIONS_LABELS_DIR  
 pos_labels_dir = settings.LUNA_NODULE_LABELS_DIR ,what is the value for that?
Thanks in advance

**Comment by juliandewit** [comment]
It's in the settings file
You can adjust it to your system's settings.
The data can be downloaded from LUNA and can be found in the resources dir of this project as a separate download

**Comment by bundelesneha05** [comment]
ok.Thanks you so much.
