### ISSUE TITLE
some questions about the evaluation of the malignancy of the nodules

### ISSUE THREAD

**Issue by fulingly** [juliandewit/kaggle_ndsb2017#66]
The second task of the 3d cnn network is to evaluate the malignancy of the nodules,
out_malignancy = Convolution3D(1, 1, 1, 1, activation=None, name="out_malignancy_last")(last64)
out_malignancy = Flatten(name="out_malignancy")(out_malignancy)
but in the step3_predict_nodules.py,the diameter_mm = round(p[1][i][0], 4),why the second output of the network is the diameter of the nodule,not the malignancy,if I understanding something wrong.I want your help desirely,thank you very much.

**Comment by fulingly** [comment]
> The second task of the 3d cnn network is to evaluate the malignancy of the nodules,
> out_malignancy = Convolution3D(1, 1, 1, 1, activation=None, name="out_malignancy_last")(last64)
> out_malignancy = Flatten(name="out_malignancy")(out_malignancy)
> but in the step3_predict_nodules.py,the diameter_mm = round(p[1][i][0], 4),why the second output of the network is the diameter of the nodule,not the malignancy,if I understanding something wrong.I want your help desirely,thank you very much.

Found the answer in previous comments, thanks

**Comment by juliandewit** [comment]
I started with diameter as proxy for cancer.
Later I found malignancy labels. 
I think this was a naming error
